= React Pageable Table
Patrick Grimard <pgrimard@gmail.com>
v1.1.0, 2016-01-02
:toc:
:imagesdir: assets/images
:homepage: http://patrickgrimard.com
:revnumber: {docVersion}

== Usage
Simply add the `<PageableTable/>` component to your own components as follows.

[source,javascript]
----
<PageableTable dataPath={dataPath} dataMapper={this.dataMapper} tableHeader={this.tableHeader}  onPageChange={this.handlePageChange}/>
----

== Properties

=== Data Path
The `dataPath` is a simple URL where the pageable table can fetch data from.  In your own component, you should
update `dataPath` whenever you want `<PageableTable/>` to show new data.  For example when changing page via
the `onPageChange` handler (see below or view the link:blob/master/example/app/scripts/app.js[example] for details).

=== Data Mapper
The `dataMapper` should tell `<PageableTable/>` how to construct a single data row.  It accepts 2 arguments, first
an object representing data for 1 row, and second an index that you should apply to the `<tr>` element.

[source,javascript]
----
dataMapper(sw, idx) {
  return (
    <tr key={idx}>
      <td>{sw.id}</td>
      <td>{sw.name}</td>
      <td>{sw.description}</td>
    </tr>
  );
}
----

=== Table Header
The `tableHeader` should construct a header row.

[source,javascript]
----
tableHeader() {
  return (
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
    </tr>
  );
}
----

=== Page Change Handler
The page change handler should result in an updated `dataPath` that will cause your component to call it's `render()`
method, passing the new `dataPath` value to `<PageableTable/>`.
[source,javascript]
----
handlePageChange: function(page) {
  // Do something with "page" that causes dataPath to update.
},
----

[source,javascript]
----
<PageableTable dataPath={dataPath} onPageChange={this.handlePageChange}/>
----

=== Sort
The `sort` property can be used to pass an array of sorting arguments which will be concatenated with the `dataPath`.
Your backend will need to know how to accept these arguments as query parameters.

In

[source,javascript]
----
<PageableTable sort={[date,desc], [number,asc]}/>
----

Out

[source]
----
http://www.example.com/api/orders?page=0&sort=data,desc&sort=number,asc
----

=== Styling
Passing a `className` property to `<PageableTable/>` will append the value to the `className` property of the
underlying `<table>` element.

In

[source,javascript]
----
<PageableTable className="my-class"/>
----

Out

[source,html]
----
<table className="my-class">
----